name: Workflow Demo

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create a text file
      run: echo "Hello, world!" > hello.txt

    - name: Archive text file
      uses: actions/upload-artifact@v4
      with:
        name: hello-artifact
        path: hello.txt

  download:
    needs: build    # ✅ This job runs after the 'build' job
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: hello-artifact
        path: ./artifacts   # ✅ Download to ./artifacts

    - name: Display artifact content
      run: cat ./artifacts/hello.txt   # ✅ Show the file content
